version: '3'
services:

  launchable:
    build:
      context: .
    ports:
      - 5000:5000
    container_name: launchable-backend
    restart: always

  frontend:
    container_name: launchable-frontend
    build:
      context: ./app/static
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
